// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1--rc1
// source: backend/v1/menu.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid int64 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// @gotags: validate:"required,min=1,max=50" label:"菜单名称"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" validate:"required,min=1,max=50" label:"菜单名称"`
	// @gotags: `validate:"required,min=1,max=20" label:"icon"`
	Icon string `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty" validate:"required,min=1,max=20" label:"icon"`
	// @gotags: `validate:"required,max=50" label:"路径"`
	Path string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty" validate:"required,max=50" label:"路径"`
	// @gotags: `validate:"required,oneof=1 2" label:"状态"`
	Status   int64 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty" validate:"required,oneof=1 2" label:"状态"`
	Sequence int64 `protobuf:"varint,6,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
}

func (x *MenuCreateReq) Reset() {
	*x = MenuCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_v1_menu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MenuCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuCreateReq) ProtoMessage() {}

func (x *MenuCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_menu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuCreateReq.ProtoReflect.Descriptor instead.
func (*MenuCreateReq) Descriptor() ([]byte, []int) {
	return file_backend_v1_menu_proto_rawDescGZIP(), []int{0}
}

func (x *MenuCreateReq) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *MenuCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuCreateReq) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MenuCreateReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MenuCreateReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MenuCreateReq) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_backend_v1_menu_proto protoreflect.FileDescriptor

var file_backend_v1_menu_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x6e,
	0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91,
	0x01, 0x0a, 0x0d, 0x4d, 0x65, 0x6e, 0x75, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x70,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x32, 0x62, 0x0a, 0x04, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x5a, 0x0a, 0x0a, 0x4d, 0x65,
	0x6e, 0x75, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x19, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x13, 0x22, 0x0e, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x65, 0x6e, 0x75, 0x3a, 0x01, 0x2a, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x6f, 0x2d, 0x73, 0x69, 0x6d,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_backend_v1_menu_proto_rawDescOnce sync.Once
	file_backend_v1_menu_proto_rawDescData = file_backend_v1_menu_proto_rawDesc
)

func file_backend_v1_menu_proto_rawDescGZIP() []byte {
	file_backend_v1_menu_proto_rawDescOnce.Do(func() {
		file_backend_v1_menu_proto_rawDescData = protoimpl.X.CompressGZIP(file_backend_v1_menu_proto_rawDescData)
	})
	return file_backend_v1_menu_proto_rawDescData
}

var file_backend_v1_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_backend_v1_menu_proto_goTypes = []interface{}{
	(*MenuCreateReq)(nil), // 0: backend.v1.MenuCreateReq
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_backend_v1_menu_proto_depIdxs = []int32{
	0, // 0: backend.v1.Menu.MenuCreate:input_type -> backend.v1.MenuCreateReq
	1, // 1: backend.v1.Menu.MenuCreate:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_backend_v1_menu_proto_init() }
func file_backend_v1_menu_proto_init() {
	if File_backend_v1_menu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_backend_v1_menu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MenuCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backend_v1_menu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_v1_menu_proto_goTypes,
		DependencyIndexes: file_backend_v1_menu_proto_depIdxs,
		MessageInfos:      file_backend_v1_menu_proto_msgTypes,
	}.Build()
	File_backend_v1_menu_proto = out.File
	file_backend_v1_menu_proto_rawDesc = nil
	file_backend_v1_menu_proto_goTypes = nil
	file_backend_v1_menu_proto_depIdxs = nil
}
