// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go-sim/internal/biz"
	"go-sim/internal/conf"
	"go-sim/internal/data"
	"go-sim/internal/server"
	"go-sim/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewMysql(confData, logger)
	dataData, cleanup, err := data.NewData(db, confData, logger)
	if err != nil {
		return nil, nil, err
	}
	officerRepo := data.NewOfficerRepo(dataData, logger)
	officerUsecase := biz.NewOfficerUsecase(officerRepo, logger)
	officerService := service.NewGreeterService(officerUsecase)
	grpcServer := server.NewGRPCServer(confServer, officerService, logger)
	httpServer := server.NewHTTPServer(confServer, officerService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
